/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void ResturantName() {
        Restaurant rest=new Restaurant("Mcdonalds",5,2);
        assertEquals("Resturant Name {Mcdonalds} Rate {5.0} Price Cat {2.0$ }\n" +
                "[]",rest.toString());
    }
    @Test void ResturantReview() {
        Review rest=new Review("It is a good resturant","Baraa",2);
        assertEquals("Review {It is a good resturant} Auther {Baraa} Rate {2.0}",rest.toString());
    }
@Test void addMutiplerev(){
    Restaurant res=new Restaurant("Mcdonalds",5,2);

    res.addReview("good one","baraa",3);
    res.addReview("good food","Mohammad",5);
    res.addReview("yumy ","Hydaya",3);
    assertEquals("Resturant Name {Mcdonalds} Rate {3.6666667} Price Cat {2.0$ }\n" +
            "[Review {good one} Auther {baraa} Rate {3.0}, Review {good food} Auther {Mohammad} Rate {5.0}, Review {yumy } Auther {Hydaya} Rate {3.0}]",res.toString());
}
}
