/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance2;

public class Library {
    public static void main(String[]arg){
        Restaurant res=new Restaurant("Mcdonalds",5,2);
        res.addReview("good one","baraa",3);
        res.addReview("good food","Mohammad",5);
        res.addReview("yumy ","Hydaya",10);
        System.out.println(res);
        Shop shop=new Shop("myshop","good one",0,5);
        shop.addShoprev("good place","baraa",3);
        shop.addShoprev("good veiw","mohammad",2);
        System.out.println(shop);
        Theater mov=new Theater("batman",0);
        mov.revmovies("good","baraa",5);
        mov.PutMovies("Fast Fuirous");
        mov.PutMovies("Room");
        mov.PutMovies("Spider man");

        Theater mov2=new Theater("prime",0);
        mov2.revmovies("natat","adada",3);
        mov2.PutMovies("wsdwsdws");
        mov2.PutMovies("cdwsdcs");
        System.out.println(mov2);


        System.out.println(mov);

    }
}
